### ISSUE TITLE
arXiv testbench test run

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1139]
**[Meta-issue]** bookkeeping the various problems and patches I am filing in as PRs, since the list is getting notable. All of these were spotted while studying the cortex reports on 10,000 arXiv document conversion, as seen at:
https://corpora.mathweb.org/corpus/arxiv_testbench/tex_to_html

### Feature-level enhancements
1. [x] Raw support for `tcilatex`, expected to be present by some arXiv sources #1129 
2. [x] Detect derivative binding names, when a file is missing, and fallback to the mainstream binding name when possible #1124 (reported by Ben)
3. [x] Improve lexeme serialization for arrays and textual sub-fragments #1131 

### Fatal-level patches
 1. [x] Robust `xml:id` attributes when parent counters are undefined #1130 
 2. [x] Proper parsing of \fmtversion and avoid infinite loop when mouths are wrongly empty #1132 
 3. [x] Proper package options regex split, (side-effecting into alignment Fatals) #1133 
 4. [x] Revtex4 option should load binding (side-effecting into alignment Fatals) #1134 
 5. [x] Plain argument content for `\unit` (side-effecting into 100+ math error Fatals) #1136 
 6. [x] Simple load of pgf.sty leads to Fatal on texlive 2018 (regression, #1143 )
 7. [x] `{picture}` macro argument signatures #1146 

### Error-level patches
 1. [x] Plain argument content for `\object` (avoiding malformed `ltx:XMTok` error) #1137
 2. ~~DefMath primitives should be error-free in text mode, patch `\And` and `\dots` in amsmath (malformed `ltx:XMTok` error)~~ #1138 (dots patched in master, `\And` was misdiagnozed)
 3. Localized search for `.bib` files #1140 
 4. [x] Keep script anchoring `{}` groups in math expressions (formulas were wrongly considered double-script errors) #1141 
 5. [x] Math mode switches in aa equations, and paragraph-type table cells #1142 

### Maintenance
  1. [x] symbolscan has fallen behind the public API of latexml #1135

**Comment by dginev** [comment]
All done and merged! Thanks to Bruce for mentoring and accepting the patches.

A new run over the testbench could be summarized as:
 - Fatals are down 0.64% , from 5.54% to 4.9%
 - Errors are down 1.1%, from 30.74% to 29.64%

I also managed to resolve a regression related to bookkeeping invalids in cortex in the process, so all in all a productive session. 

Hard to spot any mid-tier patches from the testbench, so might as well wrap up here, and get ready for the big arXiv rerun with the release of 0.8.4
