### ISSUE TITLE
[arXiv] community article upgrades

### ISSUE THREAD

**Issue by dginev** [brucemiller/LaTeXML#1685]
I was doing some good samaritan user support [on twitter](https://twitter.com/BarakShoshany/status/1446572969434796043) today, in order to prioritize some community requests along with the statistical imperatives.

Reports based on arxiv-vanity on october 8, 2021:

articles failed to render:
  - [x] [1811.04360](https://ar5iv.org/html/1811.04360) -- infinite loop in tikz (PR #1701)
  - [x] [1904.06386](https://ar5iv.org/html/1904.06386) -- infinite loop in tikz (PR #1701)
  - [x] [1912.02922](https://ar5iv.org/html/1912.02922) -- infinite loop in tikz (PR #1701)
  - [x] [1911.11590](https://ar5iv.org/html/1911.11590) -- this seems to already be better

code blocks are messed up:
  - [x] [2105.00613](https://ar5iv.org/html/2105.00613)

I'm hoping to debug these in a couple of weeks, so recording them here as a placeholder and getting the assignment flag.
